---
number:     66
title:       Shrimping (hand-built Arduino) workshop for children and adults
description: |
            <p><a href="http://start.shrimping.it/project/blink/build.html">The shrimp</a> is a small Arduino compatible computer built on a breadboard.</p>
            <p>In this 1.5 hour workshop you will learn how to build and program a Shrimp, with two projects. Bring your children (7 and up)</p>
sessions: |
            <h3>Workshop details</h3>
            <p id="workshopproject1">Project 1. <a href="http://start.shrimping.it/project/blink/index.html">Flashing LED</a>. This project is to get you started. You will build the shrimp, and get it to flash a small LED. You will then learn how to program the shrimp to change how the LED flashes.</p>

            <p id="workshopproject2">Project 2. <a href="http://start.shrimping.it/project/pov/index.html">Persistence of vision</a>. You will add a line of LEDs to your shrimp, and program it to flash them at very high speed, so when waved in the air it spells out a message.</p>

            <p>At the end of the workshop you can take your shrimp home with you.</p>
            <p>This workshop is suitable for anyone over the age of 7. For children 7-11, it is very much about following instructions to build a computer. For older children (our record is 92), you will start to understand how a computer works and want to explore how much it can be modified.</p>

            <h3>Pre-requisits</h3>
            <p>BCS Open Source SG will supply the Shrimping kits. You'll need to bring a laptop with the free <a href="https://www.arduino.cc/en/Main/Software">Arduino IDE</a> installed</p>

            <h3>Speaker Biographies</h3>
            <p id="JeremyBennett" class="vcard"><a class="fn url" title="Jeremy Bennett" - Twitter" href="http://twitter.com/jeremypbennett">Dr Jeremy Bennett</a> is Chair of the BCS Open Source Specialist Group. He is also Chief Executive of Embecosm who provide open source compiler development services. A former academic he is author of the standard textbook "Introduciton to Compiling Techniques" (McGraw-Hill 1990, 1995, 2003).</p>
            <p><strong>Note: Please aim to arrive by 18:15 as the event will start at 18:30 prompt.</strong></p>
            <p><strong>Closing date for bookings is Thursday 19 April 2018 at 08:30 am. No more bookings will be taken after this date. For overseas delegates who wish to attend the event please note that BCS does not issue invitation letters</strong></p>

date:        19 April 2018
dtstart:     2018-04-19T18:00:00Z
dtend:       2018-04-19T20:00:00Z
start:       18:30
end:         20:00
pubdate:     Wed, 09 March 2018 17:20:00 GMT
updated:     2018-03-09T10:15:00Z
location:    BCS London
isoduration: P0Y0M0DT08H00M00S
generator:   vi
registration: https://ossg190418.eventbrite.co.uk
upcoming:
lanyrd:

tags:
    - workshop
    - arduino
    - shrimping
