---
number:     69
title:      Members' Lightning Talks
description: |
            <p>We don't usually do a September meeting, but we thought it would be
            interesting to hear from our members about the projects that they have been
            working on over the year. We're delighted to welcome a range of speakers who will
            spend 10 or 15 minutes discussing their projects.
            <p>This is a joint meeting with the <a href="https://ossg.bcs.org/">British Computer Society Open Source Specialist Group</a>.</p>
sessions: |
            <h3>Hammerspoon: Staggeringly powerful macOS desktop automation</h3>
            <p id="hammerspoon"><a href="http://www.hammerspoon.org">Hammerspoon</a> exposes many parts of macOS to the simple scripting language Lua.
            Its goal is to make the most powerful and flexible tool for serious power users
            to automate and customise as many things as possible. In this talk we'll look
            at the history of automation on Apple computers, how Hammerspoon works, and
            some of the excellent things it can help you do. Of course, it's Open Source,
            so you can also jump in and help make it even better!</p>

            <p id="ChrisJones" class="vcard"><a class="fn url" title="Chris Jones - Twitter" href="https://twitter.com/cmsj">Chris Jones</a>
            has been creating, using, and advocating for Open Source software,
            since the mid-1990s. He's spent the last 12 years of his professional life
            working on/with Open Source - the first half at Canonical (creators of Ubuntu)
            and since then working on OpenStack at HP and Red Hat.<br />

            After 13 years of zealously running only Linux on his desktops/laptops, he has
            spent the last 8 years recovering as a macOS user, but has nevertheless
            retained his passion for contributing to Open Source.</p>

            <h3>Cooking with a touch of science and a dash of engineering.</h3>
            <p id="sousvide">Sous vide (under vacuum) is a technique that places food into a temperature
            controlled water bath. The vacuum bit isn't that important, and squeezing the
            air out of a zip lock bag is generally sufficient; but precise temperature
            control is essential to ensure that the right proteins are denatured. The
            thermostat in a typical piece of kitchen equipment is nowhere near good enough,
            but add a sensor (immersible temperature gauge), an actuator (433MHz remote
            control socket), some control software and a dev board to run it on and you
            have the ability to cook perfect steaks, eggs, fish or whatever.</p>

            <p id="ChrisSwan" class="vcard"><a class="fn url" title="Chris Swan - Twitter" href="https://twitter.com/cpswan">Chris Swan</a>
            has been tinkering with electronics since he was a small child, and
            got into software when he realised that it was necessary to make hardware do
            interesting things. In his day job as CTO for Global Delivery for DXC
            Technology he's bringing a large services company and its customers into a
            world of DevOps and Infrastructure as Code. On evenings and weekends he can
            often be found making some sort of project around a dev board, with a
            particular fondness for Raspberry Pis.</p>

            <h3>Building an Open Source Electric Surfboard</h3>
            <p id="surfboard">With the increasing availability of 3D printers and the wide variety of
            components available over the internet, how hard is it to build an electric
            surfboard? This talk will cover the design and construction of an open-source
            electric surfboard from the concept to hitting the sea, including some of the
            challenges met along the way, especially those to do with managing lots of
            electricity very close to lots of water. The project can be found on GitHub at
            <a href="https://github.com/largeostrich/openelectricsurfboard">https://github.com/largeostrich/openelectricsurfboard</a> and
            <a href="https://github.com/largeostrich/openwaterjet">https://github.com/largeostrich/openwaterjet</a>.</p>

            <p id="PeterBennett">Peter Bennett (thelargeostrich) is currently studying Mining Engineering at
            Camborne School of Mines, University of Exeter. He has a long standing interest
            in open source technology, particularly 3D printing and electronics. He
            previously reimagined peripherals for the EDSAC using 3D printing and arduino
            for ChipHack at Wuthering Bytes 2017.</p>

            <h3>Jumbo Servo - I2C position control</h3>
            <p id="jumboservo">When Andy needed a really big servo, rather than spend a fortune on an
            industrial monster, he decided to make one. As it would be used with a
            Raspberry Pi or Microcontroller he decided it would be digitally controlled
            rather than the usual analogue pwm.</p>

            <p id="AndyClark">Andy Clark has been Making and Repairing in a shed at the bottom of the garden
            for the last 10 years. The code and designs for his often quirky and enchanting
            projects can be found on GitHub and documented on the Workshopshed blog.</p>

            <h3>Next Generation Storage Interfaces</h3>
            <p id="storage">The efficient, convenient, and robust execution of data-driven workflows and
            enhanced data management are key for productive in computer-aided RD&E.  Still,
            the storage stack is based on the low-level POSIX I/O (or objects in cloud
            storage).  This talk introduces chances for establishing an open
            community-driven next-generation storage interface in a similar fashion to the
            existing forums.  The forum would bring together vendors, storage experts, and
            users to discuss key features of the API and establish governance strategies.
            The envisioned coarse-grained API aims to overcome current obstacles for highly
            parallel workflows but would be beneficial also in the domain of big data and
            even desktop PC.  It bears the opportunity to create a new ecosystem.</p>

            <p id="JulianKunkel">Dr. Kunkel is a Lecturer at the Computer Science Department at the University
            of Reading. Previously, he worked as postdoc in the research department of the
            German Climate Computing Center (DKRZ) that partners with the Scientific
            Computing group at the Universität Hamburg. He manages several research
            projects revolving around High-Performance Computing and particularly
            high-performance storage.  Julian became interested in the topic of HPC storage
            in 2003, during his studies of computer science. Besides his main goal to
            provide efficient and performance-portable I/O, his HPC-related interests are:
            data reduction techniques, performance analysis of parallel applications and
            parallel I/O, management of cluster systems, cost-efficiency considerations,
            and software engineering of scientific software.</p>

            <h3>Upspin: a personal storage and sharing system</h3>
            <p id="upspinio"><a href="https://upspin.io">Upspin</a> tries to address the shortcomings of sharing,
            privacy, and availability of data on the internet, in the modern day. Whether it's making state available across
            multiple computers or sharing with other parties, Upspin is a personal namespace which can accomodate and be built upon.</p>

            <p id="SevanJaniyan" class="vcard"><a class="fn url" title="Sevan Janiyan - Website" href="https://www.sevanjaniyan.co.uk">
            Sevan Janiyan founder of <a href="http://www.venture37.com/" title="Venture 37 website">Venture 37</a>, which provides
            system administration & consultancy services. As a fan of operating systems and computers with different CPU architectures,
            in his spare time he maintains builds of open source software on a variety of systems featuring PowerPC, SPARC and ARM CPUs.</p>

            <h3>A Plan 9 C Compiler for RISC-V</h3>
            <p id="plan9compiler">The Plan 9 operating system was developed at Bell Labs in the 1980s using a new
            C compiler written by Ken Thompson, which was also later used to implement the
            kernel of the Inferno operating system and to bootstrap early releases of the
            Go language.  Like Plan 9 itself, the compiler is highly portable, elegantly
            minimalist, lightweight and quick.  The ARM version, for example, is about
            21,000 lines of code and compiles itself in 15 seconds on a Raspberry Pi 3.
            This talk will describe the exercise of re-targeting the Plan 9 C compiler to
            generate code for the RISC-V open instruction set architecture.</p>

            <p id="DrRichardMiller">Dr Richard Miller learned C in 1977 while re-targeting (and re-hosting)
            Dennis Ritchie's original Unix C compiler from the PDP-11 to the Interdata
            7/32.  Since then he has re-targeted Unix and Plan 9 C compilers for various
            other CPUs from NS 16032 to Nios II.</p>

            <p><strong>Note: Please aim to arrive by 18:15 as the event will start at 18:30 prompt.</strong></p>

date:        13 September 2018
dtstart:     2018-08-13T18:00:00Z
dtend:       2018-07-13T20:00:00Z
start:       18:30
end:         20:00
pubdate:     Wed, 22 August 2018 17:45:04 GMT
updated:     2018-08-23T31:56:57Z
location:    BCS London
isoduration: P0Y0M0DT01H30M00S
generator:   vi
registration: https://ossg130918.eventbrite.co.uk/
upcoming:
lanyrd:

tags:
    - makers
